### ISSUE TITLE
Duplicate skill entry for archmagefb

### ISSUE THREAD

**Issue by Lechros** [oleneyl/simaple#54]
불독의 '메디테이션' 스킬이 default_active_skill에 DefaultActiveSkill로, components에 BuffSkillComponent로 중복됩니다.
추가 구현 전에 Default active skill과 buff skill을 구분하는 기준을 정의하면 좋을 것 같습니다.

**Comment by oleneyl** [comment]
Buff Skill: 전투 중에만 발동 가능한 버프 (마을에서 스탯창을 켰을 때 확인 할 수 없는 부류)
Default Active Skill: 전투 중에만 발동 가능하지만 상시로 발동되어, 스펙 최적화에서 사용하는것이 마땅한 버프 (마을에서 스탯창을 켰을 때 확인할 수 없는 부류)
